testing
saml4u/testing pull request #1
Opened 2021-11-19 16:22 UTC by cgiroux86

2021-11-19 16:25 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot03Z28M7MEkzR41DW:brarzdg) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
> ```Markdown
> # testing
> 
> This a test repo for teams
> ```

Comment.


<!-- Sent from Reviewable.io -->

2021-11-19 16:27 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot0XH0C-bbJUtXE6s-:bh2icn1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment.
</blockquote></details>

Another comment


<!-- Sent from Reviewable.io -->

2021-11-19 16:28 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot0njG1VkyolQFYuiC:bh2icn1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

Another comment


<!-- Sent from Reviewable.io -->

2021-11-19 16:30 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
Test


<!-- Sent from Reviewable.io -->

2021-11-19 16:31 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot1Z3xCMAzd9PB_jWP:b-p04xd1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

A comment


<!-- Sent from Reviewable.io -->

2021-11-19 16:33 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot1tODD-2AWkIwF2Kz:b-x6jyr1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

A comment
</blockquote></details>

Working?


<!-- Sent from Reviewable.io -->

2021-11-19 16:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Test
</blockquote></details>

Testing
___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot03Z19G7T7deklr_P:-Mot4KCU1Lc7wB3G2xQ-:b-x6jyr1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Working?
</blockquote></details>

Working?


<!-- Sent from Reviewable.io -->

2021-11-19 16:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Testing
</blockquote></details>

Another


<!-- Sent from Reviewable.io -->

2021-11-19 16:45 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another
</blockquote></details>

Last


<!-- Sent from Reviewable.io -->

2021-11-19 16:49 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Last
</blockquote></details>

Anotgher


<!-- Sent from Reviewable.io -->

2021-11-19 16:50 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Anotgher
</blockquote></details>

Test


<!-- Sent from Reviewable.io -->

2021-11-19 17:21 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Test
</blockquote></details>

Another comment


<!-- Sent from Reviewable.io -->

2021-11-19 17:27 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

Last


<!-- Sent from Reviewable.io -->

2021-11-19 17:30 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotF1IL4X9gclg178eD:b-p04xd1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
> ```Markdown
> # testing
> 
> This a test repo for teams
> ```

A comment


<!-- Sent from Reviewable.io -->

2021-11-19 17:33 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotFfSd5LbjJu5Pp2PL:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

A comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-19 17:39 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotGz0hB5s22Qn3UfRB:bb73z13) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TEST


<!-- Sent from Reviewable.io -->

2021-11-19 17:40 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotHC0v8zInzpiCYrcP:bk0k3zo) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

Another test


<!-- Sent from Reviewable.io -->

2021-11-19 17:40 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotHLkm6KyuZmDftdBV:b-1m8w7g) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another test
</blockquote></details>

One more


<!-- Sent from Reviewable.io -->

2021-11-19 17:41 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotHVz6-DZ8hJsGrn3c:b-8az6p1) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

One more
</blockquote></details>

Again


<!-- Sent from Reviewable.io -->

2021-11-19 17:42 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r1](http://localhost:8080/reviews/saml4u/testing/1#-MotF1IL4X9gclg178eC:-MotHd6o2_Xr5paVASHa:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/ee49bfff0e5882cfda901126e14646a956506181/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Again
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-22 19:02 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Last
</blockquote></details>

Another test


<!-- Sent from Reviewable.io -->

2021-11-22 19:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another test
</blockquote></details>

Another


<!-- Sent from Reviewable.io -->

2021-11-22 19:06 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp81jMvDlH-1ZfJYhAm:-Mp81jMvDlH-1ZfJYhAn:b-srunom) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
> ```Markdown
> # testing
> 
> This a test repo for teams!
> ```

New comment


<!-- Sent from Reviewable.io -->

2021-11-22 19:09 UTC, girouxchris1017 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp82O-i2L_8YQnAUXXY:b-srunom) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
> ```Markdown
> # testing
> 
> This a test repo for teams!
> ```

New comment


<!-- Sent from Reviewable.io -->

2021-11-22 19:10 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp82fxZ-WGhmf8nThSJ:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

New comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:37 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, @girouxchris1017, and @Goldi8685)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp88qBzEhXYzfD2M4ig:b-srunom) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

New comment


<!-- Sent from Reviewable.io -->

2021-11-22 19:37 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @Goldi8685)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp88siU8K4b7kE2Iz2P:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

New comment
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 19:41 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp89nR7EoC_qgkFCzYc:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:42 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp89scjA0mbTZlKE5II:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 19:42 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp89vmV05piskPzehGy:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 19:43 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8A82r476noZmCvhB4:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:44 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8AQOH2fObMHT9iDI9:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:45 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8AWMr-qmW8CKPmU79:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 19:45 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8AhyC8FNfoJk-yDnE:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:46 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8Al_t1_T8YJlE39n3:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:47 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8B13R9XvHYvV_7ICA:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 19:47 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8B6pg49cETnpWLFFS:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8DJoo2t8w1wPaD94A:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:57 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8BMPyAIUd-tIjtzg7:b-8nyi3w) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done


<!-- Sent from Reviewable.io -->

2021-11-22 19:58 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8Dfta9xLjVfdBAKlA:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:59 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8Dhte62f99a-S3sTH:b-gxux3y) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?m


<!-- Sent from Reviewable.io -->

2021-11-22 19:59 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8Dm1t0pzhs4WdCpKw:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?m
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 19:59 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8DrG85Y-pqWPJxYRU:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 20:00 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8E1Mo4O6klEso0nFU:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 20:07 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8F_XLE3czFXpx_NiZ:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 20:10 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8GKZl4Frh5L96sWg3:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 20:10 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8GPm45DLqz1-DXaZ6:bb7110x) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?


<!-- Sent from Reviewable.io -->

2021-11-22 20:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8GfPA7LqWy-Kr9SJP:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 20:14 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8HMOo7QQE2dRQ9HEw:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-22 21:58 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp8e7ybD0_Wi9MsTCkC:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 00:54 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp9HPbY6zAOfNK2GTgh:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-23 00:57 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp9I6Zo98nzbuZ1MygG:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-23 01:02 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp9J6sx9xcqyny1FgUH:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-23 01:03 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-Mp9JMac2bn-l7ook-bL:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-23 18:58 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpD903C3KoUji7qg2eZ:b7r5xui) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Comment


<!-- Sent from Reviewable.io -->

2021-11-23 19:08 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDBqvV2JtMANQ50Pii:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-23 19:09 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDC2DrDeP4zKt6zL_K:bh2icn1) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Another comment


<!-- Sent from Reviewable.io -->

2021-11-23 19:10 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDC9pREYKksIlP5-Jm:bh2icn1) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

Another comment


<!-- Sent from Reviewable.io -->

2021-11-23 19:10 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDCJIEArKLdE0TwUMk:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 19:11 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDCT0E4Ky29GPHLRGW:bs7wuoy) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.i


<!-- Sent from Reviewable.io -->

2021-11-23 19:16 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDDa5Z-rY1qeIoOuQe:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.i
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-23 19:17 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDDvL8B3DAW_VzdKDZ:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 19:18 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDE86i2tp9mxuRxHM3:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 19:19 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDEBkGElMndWlMafYq:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-23 19:19 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDELBZ0QG6y7fiMJrw:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 19:20 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDEX0v3RaQ9ntPfJ3O:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 19:20 UTC, girouxchris1017 requested changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDE_JQ4rDjAdklBRrO:bfhqmln) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2021-11-23 20:19 UTC, cgiroux86 reviewed
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp82O-i2L_8YQnAUXXX:-MpDS-tu7FDn3LfuBFq7:b-896fix) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 20:19 UTC, girouxchris1017 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)



<!-- Sent from Reviewable.io -->

2021-11-23 20:20 UTC, girouxchris1017 approved these changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/saml4u/testing/1#-Mot1I7X4wudEg2zLoJv):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2021-11-23 20:20 UTC, girouxchris1017 approved these changes
> *[Reviewable](http://localhost:8080/reviews/saml4u/testing/1)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[README.md, line 3 at r2](http://localhost:8080/reviews/saml4u/testing/1#-Mp81jMvDlH-1ZfJYhAm:-MpDSAII9zRmLHtpqZ-G:b2nhll9) ([raw file](https://github.com/saml4u/testing/blob/f29734b5dc1570d58c6a13c698658918900c1478/README.md#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

New comment
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2021-11-23 20:21 UTC, merged